version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - mysql
      - web1
      - web2
    networks:
      - nginx-internal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    ports:
      - 80:80

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbdata:/var/lib/mysql
    networks:
      - nginx-internal
    command: "--default-authentication-plugin=mysql_native_password"

  web1:
    image: wordpress
    container_name: web1
    depends_on:
      - mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=root # should change in PROD
      - WORDPRESS_DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - WORDPRESS_DB_NAME=web1
    volumes:
      - ./wordpress/web1/:/var/www/html/
    networks:
      - nginx-internal

  web2:
    image: wordpress
    container_name: web2
    depends_on:
      - mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=root # should change in PROD
      - WORDPRESS_DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - WORDPRESS_DB_NAME=web2
    volumes:
      - ./wordpress/web2/:/var/www/html/
    networks:
      - nginx-internal

networks:
  nginx-internal:
    driver: bridge
