version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - nginx-internal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    ports:
      - 80:80
  php:
    image: php:fpm-alpine
    container_name: php
    networks:
      - nginx-internal
    volumes:
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./html:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  nginx-internal:
    driver: bridge
